# Generated by Django 3.2.9 on 2021-12-05 21:56

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(validators=[customers.models.validate_price]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transaction_number',
            field=models.CharField(max_length=15, validators=[customers.models.validate_number]),
        ),
    ]
