# Generated by Django 3.2.9 on 2021-12-05 15:09

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.FloatField(validators=[orders.models.validate_price])),
                ('title', models.CharField(max_length=64)),
                ('owner', models.IntegerField()),
            ],
        ),
    ]
